CrowdSourceDiscovery.Web/Controllers/ConnectionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CrowdSourceDiscovery.Contracts.Dtos;
using CrowdSourceDiscovery.Domain;
using CrowdSourceDiscovery.Web.Helper;
using CrowdSourceDiscovery.Web.Models;
using CrowdSourceDiscovery.Services.Interfaces;
using Microsoft.AspNet.Identity;

namespace CrowdSourceDiscovery.Web.Controllers
{
    [Authorize]
    public class ConnectionController : Controller
    {
        private readonly IConnections _connections;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly PermissionHelper _permissionHelper;

        public ConnectionController(IConnections connections, UserManager<ApplicationUser> manager, PermissionHelper permissionHelper)
        {
            _connections = connections;
            _manager = manager;
            _permissionHelper = permissionHelper;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var connections = _connections.GetAll();
            var models = connections.Select(connection => new ConnectionListModel()
            {
                ConnectionId = connection.Id,
                LinkOneTitle = connection.GetFirstLink().Title,
                LinkTwoTitle = connection.GetSecondLink().Title,
                NumberOfComments = connection.Comments.Count
            }).OrderByDescending(m=> m.NumberOfComments).ToList();

            return View(models);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ConnectionFormModel connectionModel)
        {
            var currentUserId = new Guid(User.Identity.GetUserId());
            var connection = new Connection {UserId = currentUserId};
            connection.AddComment(new Comment(connectionModel.Comment, currentUserId));
            connection.AddLinks(new Link(connectionModel.LinkOne, connectionModel.LinkOneTitle));
            connection.AddLinks(new Link(connectionModel.LinkTwo, connectionModel.LinkTwoTitle));
            _connections.Save(connection);

            return RedirectToAction("Details", new { id=connection.Id});
        }

        public ActionResult Edit(int id)
        {
            var connection = _connections.GetConnection(id);
            var connectionFormModel = new ConnectionFormModel()
            {
                ConnectionId = connection.Id,
                LinkOne = connection.GetFirstLink().Url.AbsoluteUri,
                LinkTwo = connection.GetSecondLink().Url.AbsoluteUri,
                LinkOneTitle = connection.GetFirstLink().Title,
                LinkTwoTitle = connection.GetSecondLink().Title,             
                Comment = connection.GetOriginalComment().Text           
            };

            return View(connectionFormModel);
        }

        [HttpPost]
        public ActionResult Edit(ConnectionFormModel model)
        {
           var connection = _connections.GetConnection(model.ConnectionId);
           connection.SaveOriginalComment(model.Comment);
           connection.UpdateFirstLink(new Link(model.LinkOne, model.LinkOneTitle)); 
           connection.UpdateSecondLink(new Link(model.LinkTwo, model.LinkTwoTitle)); 
         
           _connections.Save(connection);

           return RedirectToAction("Details", new { id = connection.Id });
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var connection = _connections.GetConnection(id);
            if (connection == null)
            {
                return HttpNotFound();
            }

            var connectionModel = new ConnectionViewModel()
            {
                 Id = connection.Id,
                 LinkOne = connection.GetFirstLink().Url.AbsoluteUri,
                 LinkTwo = connection.GetSecondLink().Url.AbsoluteUri,
                 LinkOneTitle = connection.GetFirstLink().Title,
                 LinkTwoTitle = connection.GetSecondLink().Title,
                 IsViewerCreator = _permissionHelper.CheckCurrentViewerIsUser(connection.UserId)
 
            };

            var commentModels = connection.Comments.Select(comment => new ConnectionViewCommentModel()
            {
                Username = _manager.FindById(comment.UserId.ToString()).UserName,
                Text = comment.Text
            }).ToList();

            connectionModel.Comments = commentModels;

            return View(connectionModel);
        }
    }
}

CrowdSourceDiscovery.Web/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CrowdSourceDiscovery.Domain;
using CrowdSourceDiscovery.Services.Interfaces;
using CrowdSourceDiscovery.Web.Models;

namespace CrowdSourceDiscovery.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly IConnections _connections;

        public SearchController(IConnections connections)
        {
            _connections = connections;
        }

        public ActionResult Index(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                return View(new List<ConnectionListModel>());
            }
            var queryInvariant = query.ToLower();
            var connections = _connections.GetAll().Where(c => c.GetFirstLink().Title.ToLower().Contains(queryInvariant)
                || c.GetSecondLink().Title.ToLower().Contains(queryInvariant));

            var model = connections.Select(connection => new ConnectionListModel()
            {
                ConnectionId = connection.Id,
                LinkOneTitle = connection.GetFirstLink().Title,
                LinkTwoTitle = connection.GetSecondLink().Title,
                NumberOfComments = connection.Comments.Count
            }).OrderByDescending(m => m.NumberOfComments).ToList();

            return View(model);
        }
	}
}

CrowdSourceDiscovery.Web/Controllers/StatisticsController.cs
using System;
using System.Web.Mvc;
using CrowdSourceDiscovery.Web.Models;
using Microsoft.AspNet.Identity;

namespace CrowdSourceDiscovery.Web.Controllers
{
    public class StatisticsController : Controller
    {
       [ChildActionOnly]
        public ActionResult ExternalMonitoring()
       {
           if (!User.Identity.IsAuthenticated)
               return View(new ExternalMonitoringModel());

           var statisticsModel = new ExternalMonitoringModel()
           {
               UserId = new Guid(User.Identity.GetUserId()),
               Username = User.Identity.GetUserName()
           };

           return View(statisticsModel);
        }
	}
}

CrowdSourceDiscovery.Web/Views/Shared/_Feedback.cshtml
<div id="feedback" ><span title="Feedback" class="btn btn-default">Feedback</span></div>

CrowdSourceDiscovery.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CrowdSourceDiscovery</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Crowd Source Discovery", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li> @Html.ActionLink("Connect", "Create", "Connection")</li>
                        <li> @Html.ActionLink("Discover", "Index", "Connection")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Crowd Source Discovery</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @Html.Action("ExternalMonitoring", "Statistics")
        @Html.Partial("_Feedback")
    </body>
</html>

CrowdSourceDiscovery.Web/Views/Shared/_ScriptFooter.cshtml
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-47893318-2', 'csdiscovery.azurewebsites.net');
    ga('send', 'pageview');

</script>
<script>
    // Include the UserVoice JavaScript SDK (only needed once on a page)
    UserVoice = window.UserVoice || []; (function () { var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true; uv.src = '//widget.uservoice.com/PZwyFrjuZASKNOcg0RN8dA.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s) })();
    
    // Set colors
    UserVoice.push(['set', {
        accent_color: '#448dd6',
        trigger_color: 'white',
        trigger_background_color: 'rgba(46, 49, 51, 0.6)',
        contact_enabled: true,
        screenshot_enabled: true,
        smartvote_enabled: true,
        post_idea_enabled: true
    }]);

    // Identify the user and pass traits
    // To enable, replace sample data with actual user traits and uncomment the line
    UserVoice.push(['identify', {
        //email:      'john.doe@example.com', // User’s email address
        //name:       'John Doe', // User’s real name
        //created_at: 1364406966, // Unix timestamp for the date the user signed up
        //id:         123, // Optional: Unique id of the user (if set, this should not change)
        //type:       'Owner', // Optional: segment your users by type
        //account: {
        //  id:           123, // Optional: associate multiple users with a single account
        //  name:         'Acme, Co.', // Account name
        //  created_at:   1364406966, // Unix timestamp for the date the account was created
        //  monthly_rate: 9.99, // Decimal; monthly rate of the account
        //  ltv:          1495.00, // Decimal; lifetime value of the account
        //  plan:         'Enhanced' // Plan name for the account
        //}
    }]);

    // Add default trigger to the bottom-right corner of the window:
   // UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);

    // Or, use your own custom trigger:
    UserVoice.push(['addTrigger', '#feedback', { mode: 'contact', menu_enabled: true }]);

    // Autoprompt for Satisfaction and SmartVote (only displayed under certain conditions)
    UserVoice.push(['autoprompt', {}]);
</script>

CrowdSourceDiscovery.Web/Views/Shared/_SearchWidget.cshtml
@using (Html.BeginForm("Index", "Search", FormMethod.Get))
{
    <div class="row">
        <div class="col-lg-8">
            <div class="input-group input-group-lg">
                <input type="text" id="query" name="query" placeholder="Search" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Discover</button>
                </span>
            </div><!-- /input-group -->
        </div>
    </div>
}